"""
Video generation tool — renders visualization HTML and records it as a video.
Uses Playwright (free, open source) for headless browser recording.
"""

import asyncio
import json
import os
from pathlib import Path


VIDEOS_DIR = Path(__file__).resolve().parents[2] / "static" / "videos"
VIDEOS_DIR.mkdir(parents=True, exist_ok=True)


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>RepoAtlas — {repo_name}</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ background: #0d1117; color: #e6edf3; font-family: 'Segoe UI', sans-serif; padding: 24px; }}
  h1 {{ font-size: 22px; color: #58a6ff; margin-bottom: 4px; }}
  .subtitle {{ color: #8b949e; font-size: 13px; margin-bottom: 28px; }}
  .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }}
  .card {{ background: #161b22; border: 1px solid #30363d; border-radius: 12px; padding: 20px; }}
  .card h2 {{ font-size: 13px; color: #8b949e; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 16px; }}
  .narrative {{ grid-column: 1 / -1; line-height: 1.7; color: #c9d1d9; font-size: 14px; }}
  .stat-row {{ display: flex; justify-content: space-between; margin-bottom: 8px; font-size: 13px; }}
  .stat-label {{ color: #8b949e; }}
  .stat-val {{ color: #e6edf3; font-weight: 600; }}
  .badge {{ display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; }}
  .badge-critical {{ background: #3d1f1f; color: #f85149; }}
  .badge-safe {{ background: #1f3d2f; color: #3fb950; }}
  canvas {{ max-height: 240px; }}
  .heatmap {{ display: flex; flex-wrap: wrap; gap: 3px; margin-top: 8px; }}
  .heat-cell {{ width: 12px; height: 12px; border-radius: 2px; }}
  .dep-list {{ font-size: 12px; color: #8b949e; }}
  .dep-item {{ padding: 4px 0; border-bottom: 1px solid #21262d; display: flex; justify-content: space-between; }}
  .commit-item {{ font-size: 12px; padding: 6px 0; border-bottom: 1px solid #21262d; }}
  .commit-hash {{ color: #58a6ff; font-family: monospace; }}
  .commit-msg {{ color: #c9d1d9; }}
  .commit-meta {{ color: #8b949e; font-size: 11px; }}
</style>
</head>
<body>

<h1>🗺 RepoAtlas AI — {repo_name}</h1>
<p class="subtitle">Visualization Report · Generated by RepoAtlas AI</p>

<div class="grid">

  <!-- Narrative -->
  <div class="card narrative">
    <h2>📋 AI Overview</h2>
    <p>{narrative}</p>
  </div>

  <!-- Language Breakdown -->
  <div class="card">
    <h2>🧩 Language Breakdown</h2>
    <canvas id="langChart"></canvas>
  </div>

  <!-- Contributor Activity -->
  <div class="card">
    <h2>👥 Contributor Activity</h2>
    <canvas id="contribChart"></canvas>
  </div>

  <!-- Commit Heatmap -->
  <div class="card" style="grid-column: 1 / -1;">
    <h2>🔥 Commit Activity Heatmap</h2>
    <div class="heatmap" id="heatmap"></div>
  </div>

  <!-- Dependency Graph summary -->
  <div class="card">
    <h2>🔗 File Dependencies</h2>
    <div class="dep-list" id="depList"></div>
  </div>

  <!-- Recent Commits -->
  <div class="card">
    <h2>📝 Recent Commits (from Trace)</h2>
    <div id="commitList"></div>
  </div>

</div>

<script>
const VIZ = {viz_json};
const TRACE = {trace_json};

// ── Language Pie Chart ─────────────────────────────
const langData = VIZ.language_breakdown.slice(0, 8);
new Chart(document.getElementById('langChart'), {{
  type: 'doughnut',
  data: {{
    labels: langData.map(l => l.language),
    datasets: [{{ data: langData.map(l => l.lines), backgroundColor: langData.map(l => l.color) }}]
  }},
  options: {{ plugins: {{ legend: {{ labels: {{ color: '#e6edf3', font: {{ size: 12 }} }} }} }}, cutout: '60%' }}
}});

// ── Contributor Bar Chart ──────────────────────────
const contrib = VIZ.contributor_activity;
const months = [...new Set(contrib.map(c => c.month))].sort();
const authors = [...new Set(contrib.map(c => c.author))];
const colors = ['#58a6ff','#3fb950','#d29922','#f85149','#bc8cff','#39d353'];
const datasets = authors.map((author, i) => ({{
  label: author,
  data: months.map(m => {{
    const entry = contrib.find(c => c.author === author && c.month === m);
    return entry ? entry.commits : 0;
  }}),
  backgroundColor: colors[i % colors.length],
}}));
new Chart(document.getElementById('contribChart'), {{
  type: 'bar',
  data: {{ labels: months, datasets }},
  options: {{
    plugins: {{ legend: {{ labels: {{ color: '#e6edf3', font: {{ size: 11 }} }} }} }},
    scales: {{
      x: {{ ticks: {{ color: '#8b949e' }}, grid: {{ color: '#21262d' }} }},
      y: {{ ticks: {{ color: '#8b949e' }}, grid: {{ color: '#21262d' }} }},
    }},
    responsive: true,
  }}
}});

// ── Heatmap ────────────────────────────────────────
const heatmap = VIZ.commit_heatmap;
const maxCount = Math.max(...heatmap.map(h => h.count), 1);
const heatEl = document.getElementById('heatmap');
heatmap.forEach(h => {{
  const cell = document.createElement('div');
  cell.className = 'heat-cell';
  const intensity = h.count / maxCount;
  const g = Math.round(57 + intensity * (211 - 57));
  cell.style.background = h.count === 0 ? '#161b22' : `rgb(14, ${{g}}, 63)`;
  cell.title = `${{h.date}}: ${{h.count}} commit(s)`;
  heatEl.appendChild(cell);
}});

// ── Dependency list ────────────────────────────────
const deps = VIZ.dependency_graph;
const depEl = document.getElementById('depList');
depEl.innerHTML = `<div class="dep-item"><span>Total files</span><span>${{deps.node_count}}</span></div>
  <div class="dep-item"><span>Import connections</span><span>${{deps.edge_count}}</span></div>`;
deps.edges.slice(0, 8).forEach(e => {{
  depEl.innerHTML += `<div class="dep-item"><span style="color:#58a6ff">${{e.source.split('/').pop()}}</span>
    <span>→ ${{e.target.split('/').pop()}}</span></div>`;
}});

// ── Commits ────────────────────────────────────────
const commitEl = document.getElementById('commitList');
(TRACE.commits || []).slice(0, 6).forEach(c => {{
  commitEl.innerHTML += `<div class="commit-item">
    <span class="commit-hash">${{c.short_hash}}</span>
    <span class="commit-msg"> ${{c.message}}</span><br>
    <span class="commit-meta">${{c.author}} · ${{c.date ? c.date.slice(0,10) : ''}}</span>
  </div>`;
}});
</script>
</body>
</html>"""


async def render_video(viz_data: dict, trace_data: dict, repo_name: str) -> str:
    """
    Render the visualization HTML in a headless browser and record a video.

    Args:
        viz_data: Output from run_visualization()
        trace_data: Output from run_trace()
        repo_name: Name to display in the video

    Returns:
        Path to the saved .webm video file (relative to static/videos/)
    """
    try:
        from playwright.async_api import async_playwright
    except ImportError:
        raise RuntimeError("Playwright not installed. Run: pip install playwright && playwright install chromium")

    html = HTML_TEMPLATE.format(
        repo_name=repo_name,
        narrative=viz_data.get("narrative", "").replace("{", "{{").replace("}", "}}"),
        viz_json=json.dumps(viz_data),
        trace_json=json.dumps(trace_data),
    )

    video_filename = f"{repo_name.replace('/', '_')}.webm"
    video_path = VIDEOS_DIR / video_filename

    async with async_playwright() as p:
        browser = await p.chromium.launch()
        context = await browser.new_context(
            viewport={"width": 1280, "height": 800},
            record_video_dir=str(VIDEOS_DIR),
            record_video_size={"width": 1280, "height": 800},
        )
        page = await context.new_page()
        await page.set_content(html, wait_until="networkidle")

        # Scroll slowly for a nice video
        await page.evaluate("window.scrollTo({top: 0, behavior: 'smooth'})")
        await asyncio.sleep(2)
        await page.evaluate("window.scrollTo({top: document.body.scrollHeight, behavior: 'smooth'})")
        await asyncio.sleep(3)
        await page.evaluate("window.scrollTo({top: 0, behavior: 'smooth'})")
        await asyncio.sleep(1)

        await context.close()
        await browser.close()

    # Playwright saves video with a generated name — find and rename it
    for f in VIDEOS_DIR.glob("*.webm"):
        if f.name != video_filename:
            f.rename(video_path)
            break

    return f"/static/videos/{video_filename}"
